# Generated by Django 2.2 on 2019-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_u', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='by_username',
            field=models.TextField(),
        ),
    ]
